[project]
name = "Lottery"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/mnt/d/BlockChain/Stacks/Lottery/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.random-number]
path = "contracts/random-number.clar"

[contracts.lottery]
path = "contracts/lottery.clar"
depends_on=["random-number"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
